### ISSUE TITLE
Downloads simultâneos

### ISSUE THREAD

**Issue by bannedgame** [mlg404/whatsapp-music-bot#10]
Como faço para colocar + de 1 download simultâneo, já tentei alterar no \src\main  -  maxParallelDownload , porém continua baixando somente 1

**Comment by mlg404** [comment]
Não está implementado.
Você pode remover o IF que checa se está sendo efetuado algum download no momento
```js
if (downloadStatus.downloading) {
  return message.reply(text.MESSAGE_WAIT_QUEUE);
}
```

E aumentar o maxParallelDownload
