### ISSUE TITLE
erro videoDetails.thumbnail.thumbnails

### ISSUE THREAD

**Issue by andrevitor98** [mlg404/whatsapp-music-bot#13]
da o erro `videoDetails.thumbnail.thumbnails` will be removed in a near future release, use `videoDetails.thumbnails` instead.
Error: spawn /usr/bin/ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[ERROR] 10:23:54 Error: spawn /usr/bin/ffmpeg ENOENT

o ffmpeg esta no path certo e ta tudo certinho, oq eu posso fazer ?

**Comment by Sordinni** [comment]
Esse **videoDetails.thumbnail.thumbnails** é só um aviso nada de mais. Mas  erro do **ffmpeg** é que ele não tá conseguindo encontrar. Ou você não instalou o **ffmpeg ou está com o path errado.**

**Comment by mlg404** [comment]
We are working on a new version correcting bugs. 
I will ask u to just wait until there
ETA: next week
