### ISSUE TITLE
Increase 15 minute time limit

### ISSUE THREAD

**Issue by GamingBrothersYT** [mlg404/whatsapp-music-bot#14]
Is it possible to increase the music time limit so that the bot can download musics that are more than 15 minutes length ?

![longest](https://user-images.githubusercontent.com/69981229/116805996-e355a280-ab47-11eb-8d4f-d1a93d73ae66.gif)

**Comment by mlg404** [comment]
You just need to change this line:
```if (duration.seconds >= 900)

But i don't remember if ytdl have a limiter too

**Comment by GamingBrothersYT** [comment]
I didnt get you. Which line to change ?

**Comment by GamingBrothersYT** [comment]
I got it.. nvm
You just need to change the number of seconds in main.ts Line 62
