### ISSUE TITLE
Error: spawn /usr/bin/ffmpeg ENOENT

### ISSUE THREAD

**Issue by 123sachithra123** [mlg404/whatsapp-music-bot#15]
Successfully connected!

`videoDetails.thumbnail.thumbnails` will be removed in a near future release, use `videoDetails.thumbnails` instead.
Error: spawn /usr/bin/ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[ERROR] 23:24:57 Error: spawn /usr/bin/ffmpeg ENOENT

if the path is  wrong how I give a path 
thank you

**Comment by mlg404** [comment]
You need to configure your ffmpegPath. Remeber to previously download and instal ffmpeg (for convertions).

Just install ffmpeg and pass  the installation path to ffmpegPath

**Comment by 123sachithra123** [comment]
![Screenshot 2021-05-05 002949](https://user-images.githubusercontent.com/52576588/117055691-0b582800-ad39-11eb-8369-6c48fe94aa03.png)
 this is my path what is wrong, i also add the path to environment variables
