### ISSUE TITLE
nao encontrado, tente novamente

### ISSUE THREAD

**Issue by chicken999** [mlg404/whatsapp-music-bot#2]
im receiving this message every time i type !play songname.
i console.log opts and it throws this message:
  _data: { videos: [], playlists: [], channels: [] }

any idea about how to fix this issue?

note: i tried from a different ip to discard if it was a ban from youtube.

**Comment by mlg404** [comment]
Reinstall yt-search package

**Comment by chicken999** [comment]
> 
> 
> im receiving this message every time i type !play songname.
> i console.log opts and it throws this message:



> 
> 
> Reinstall yt-search package

fixed after uninstalling yt-search cleaning cache and installing again, thank you so much! problem solved

**Comment by Sytxx** [comment]
not fixed

**Comment by mlg404** [comment]
Show me your package.json, please
