### ISSUE TITLE
somethings wrong but dont know

### ISSUE THREAD

**Issue by jafri-jahan-s** [mlg404/whatsapp-music-bot#22]
![IMG_20210708_134011__01](https://user-images.githubusercontent.com/56589554/124887400-c4b1d300-dff2-11eb-961b-3c1b36f2a37c.jpg)

**Comment by BharatSinghG** [comment]
same error has anyone found any solution

**Comment by jafri-jahan-s** [comment]
i did a clean install in a vm still getting the same error

**Comment by DevAmiyo** [comment]
Same issue

**Comment by shinjithpakkam** [comment]
Same issue. I tried solving it in every possible way 😐.
But my friend who tried along with me has got a successful working bot... Hope someone could solve this : )

**Comment by Sordinni** [comment]
Just run **npm i whatsapp-web.js** and try again.

**Comment by jafri-jahan-s** [comment]
> Just run **npm i whatsapp-web.js** and try again.

Whatsapp not even recognising the qr code😭

**Comment by Sordinni** [comment]
> > Just run **npm i whatsapp-web.js** and try again.
> 
> Whatsapp not even recognising the qr code😭

jafri, use a old version off WhatsApp. New versions are coming with multi devices. I will use 2.21.21.19 until it becomes obsolete.

**Comment by mlg404** [comment]
We are working on a new version correcting bugs. 
I will ask u to just wait until there
ETA: next week

**Comment by jafri-jahan-s** [comment]
Awesome 👍
