### ISSUE TITLE
failed to start | yarn start

### ISSUE THREAD

**Issue by sqdnoises** [mlg404/whatsapp-music-bot#26]
![IMG_20210908_084118](https://user-images.githubusercontent.com/85015626/132440443-9c33083b-8fb4-4602-9f62-e7c02d863531.jpg)
I did everything correctly but still I got an error, I don't know what this error means but can you help me please?

**Comment by DevAmiyo** [comment]
It says it failed to launch the browser check chromium path and variable maybe...

...
Edit: Are you using it on your phone with termux ?

**Comment by mlg404** [comment]
Try new version

https://github.com/mlg404/whatsapp-music-bot/tree/develop
