### ISSUE TITLE
My phone recognised the QR code, it didn´t work and this shows

### ISSUE THREAD

**Issue by GKW9889** [mlg404/whatsapp-music-bot#27]
![Screeenshot](https://user-images.githubusercontent.com/94145200/141380329-15887974-ef50-4cdb-89bb-7acdc02b34a1.jpg)

**Comment by mlg404** [comment]
We are working on a new version correcting bugs. 
I will ask u to just wait until there
ETA: next week

**Comment by DevAmiyo** [comment]
> We are working on a new version correcting bugs. I will ask u to just wait until there ETA: next week

- **Week 4 of waiting for @mlg404 to update the repository....**

**Comment by mlg404** [comment]
> > We are working on a new version correcting bugs. I will ask u to just wait until there ETA: next week
> 
> * **Week 4 of waiting for @mlg404 to update the repository....**

https://github.com/mlg404/whatsapp-music-bot/tree/develop
