### ISSUE TITLE
Fails to initialize bot 

### ISSUE THREAD

**Issue by shnjd** [mlg404/whatsapp-music-bot#31]
I've tried installing this for many times. I think the problem is from client side.

![Screenshot (9)](https://user-images.githubusercontent.com/84950675/151657801-b39f5e0f-0d8f-4ccb-8769-a94b7d647495.png)
It always end up with a error message like this. I've also turned of two-step verification in my app for making connection easier..
Someone please solve this problem. Thanks in advance.

**Comment by mlg404** [comment]
Fixed on #32 
Also, try node 17 if error persists
