### ISSUE TITLE
Não Instala

### ISSUE THREAD

**Issue by Marcus-dev-BR** [mlg404/whatsapp-music-bot#8]
Já tentei de tudo instalar, mas não consigo de jeito algum
![Captura de tela 2020-10-18 102120](https://user-images.githubusercontent.com/73065711/96368708-c1587d80-112b-11eb-9fb5-efd903855f4d.png)

**Comment by mlg404** [comment]
Você ŕecisa instalar o ffmpeg em seu computador e depois configurar o caminho para ele no index.js
